import React from "react";
import Layout from "../components/layout";
import HeaderTwo from "../components/header/header-two";
import StickyHeader from "../components/header/sticky-header";
import PageHeader from "../components/page-header";
import Bastforpoolen from "../components/bast-for-poolen";
import BrandCarousel from "../components/brand-carousel";
import { Container, Row, Col } from "react-bootstrap";
import Footer from "../components/footer";
import Head from "next/head";

const Betingelser = () => {
    return (
        <>
            <Head>
                <title>Betingelser for brug</title>
                <meta name="title" content="Betingelser - GreenPlank.se" />
                <meta name="description" content="Följande användarvillkor, alla policyer och villkor införlivade som referens, och eventuella efterföljande ändringar av det föregående." />
            </Head>
            <Layout pageTitle="Betingelser for brug">
                <HeaderTwo />
                <PageHeader title="Betingelser for brug" crumbTitle="Betingelser for brug" />
                <StickyHeader />
                <section className="about-one pt-120 pb-40">
                    <Container>
                        <Row style={{ marginBottom: "4em" }}>
                            <Col lg={12}>
                                <h2>Betingelser for brug</h2>
                                <div className="mb-30">
                                    <h5>Velkommen til Green Plank webstedet (“Site”). FØR DU KAN BRUGE WEBSTEDET, SKAL DU LÆSE, FORSTÅ OG GODKENDER AT VÆRE BUNDET AF FØLGENDE BETINGELSER FOR BRUG, ALLE POLITIKER OG BETINGELSER INDLEDT MED REFERENCE, OG ALLE efterfølgende ændringer til det foregående. Ved at bruge dette websted angiver du din accept af disse brugsbetingelser. Hvis du ikke er enig i nogen del af disse brugsbetingelser, BRUG IKKE DETTE WEBSTED ELLER DOWNLOADING AF MATERIALER FRA DET.</h5>
                                    <h5 className="mb-30 mt-30">Green Plank AB (“Green Plank”) forbeholder sig ret til at ændre eller ændre vilkårene og betingelserne i brugsbetingelserne eller enhver politik eller retningslinje på webstedet, når som helst og efter eget skøn. Enhver ændring eller ændring vil være effektiv ved offentliggørelse af revisioner og meddelelse om sådanne ændringer på webstedet. Din fortsatte brug af dette websted efter offentliggørelsen af ​​dets ændringer eller modifikationer vil udgøre din accept af sådanne ændringer eller ændringer. Derfor bør du ofte gennemgå vilkårene for brug og gældende politikker fra tid til anden for at forstå de vilkår og betingelser, der gælder for din brug af webstedet.</h5>
                                    <h5 className="mb-30 mt-30">Disse brugsbetingelser ændrer ikke på nogen måde vilkårene eller betingelserne i nogen anden aftale, du måtte have med Green Plank for andre produkter eller tjenester.</h5>
                                    <h5 className="mb-30 mt-30">Spørgsmål eller kommentarer om webstedet eller dets indhold skal rettes til info@GreenPlank.dk</h5>
                                    <h5 className="mb-30 mt-30"><strong> INKORPORERET POLITIK ELLER VILKÅR
                                    </strong></h5>
                                    <h3 className="mb-30 mt-30">Fortrolighedspolitik</h3>
                                    <h5 className="mb-30 mt-30"> Green Plank tror stærkt på at beskytte brugernes privatliv og give dig besked om Green Planks indsamling og brug af data, herunder personlige oplysninger, indsamlet fra webstedet. Derfor har Green Plank vedtaget en fortrolighedspolitik, som du skal henvise til for at forstå, hvordan Green Plank bruger og indsamler oplysninger.</h5>
                                    <h3 className="mb-30 mt-30">Salgsbetingelser</h3>
                                    <h5 className="mb-30 mt-30">Alle ordrer, der afgives via webstedet, er underlagt Green Planks salgsbetingelser. Du bør henvise til vores salgsbetingelser for at lære mere om gældende produktgarantier, vores returpolitik og forsendelsesbetingelser. Ved at bestille og / eller acceptere levering af produkterne accepterer du at være bundet af disse salgsbetingelser, returpolitik, forsendelsesbetingelser inklusive ansvarsfraskrivelser og begrænsninger i ansvar deri. Salgsbetingelserne, returpolitikken og forsendelsesbetingelserne kan ændres uden forudgående varsel til enhver tid efter Green Planks eget skøn, så du bør gennemgå salgsbetingelserne, returpolitikken og forsendelsesbetingelserne hver gang du foretager et køb.</h5>
                                    <h3 className="mb-30 mt-30">Websitevilkår (brugeraftale)</h3>
                                    <ul>
                                        <strong>1. </strong>Ved at downloade, kopiere, reproducere, distribuere, udskrive eller bruge materiale ejet af Green Plank AB (Green Plank) og specifikt gjort tilgængeligt på Green Plank-webstedet, bekræfter du din accept af denne brugeraftale og accepterer alle brugsbetingelser i denne brugeraftale.
                                        <br />
                                        <strong>2. </strong>Materiale betyder arbejde, hvad enten det er skrevet, grafisk, fotografisk, visuelt, lyd og ethvert emne ejet af Green Plank, der vises eller er blevet implementeret på GreenPlank.eu-webstedet.<br />
                                        <strong>3. </strong>Som det er tilfældet med alt materiale på GreenPlank.eu-webstedet, er det beskyttet af ophavsret.<br />
                                        <strong>4. </strong>Tilladelse (tilladelse) til at bruge Green Planks webstedsmateriale gives betinget som beskrevet i disse brugsbetingelser.<br />
                                        <strong>5. </strong>Intet i tildelingen af ​​denne Tilladelse udgør et uigenkaldeligt privilegium eller en ret fra brugerens side.<br />
                                        <strong>6. </strong>Green Plank forbeholder sig ret til at tilbagekalde tilladelse til at bruge ethvert af dets ophavsretligt beskyttede materiale, hvis Green Plank finder ud af, at brugeren af ​​det ophavsretligt beskyttede materiale har misbrugt privilegiet til at bruge materialet på den måde, der er beskrevet i disse brugsbetingelser.<br />
                                        <strong>7. </strong>Brugeren af ​​det ophavsretligt beskyttede materiale efter varsel fra Green Plank ophører straks og afstår fra at bruge materialet, og hvis materialet vises på et websted, skal materialet straks fjernes fra hjemmesiden uden unødig forsinkelse.<br />
                                    </ul>
                                    <h3 className="mb-30 mt-30">FORPLIGTELSER OM MEDLEMSKONTO</h3>
                                    <h5 className="mb-30 mt-10">Når du har accepteret disse brugsbetingelser, kan du åbne en medlemskonto under afsnittet Medlemskab på webstedet (“medlemskontoen”) som privat kunde eller grossist / forhandler. Som en del af medlemsregistreringen kan den person, der åbner medlemskontoen på webstedet (“administratoren”) vælge at give os oplysningerne om andre brugere, der er autoriserede til at udføre bestemte funktioner på administratorens vegne gennem medlemskontoen ( “Autoriserede brugere”). Administratoren skal specifikt vælge, hvilke funktioner hver autoriseret bruger har beføjelse til at udføre via webstedet.</h5>
                                    <h5 className="mb-30 mt-10">Autoriserede brugere kan få adgang til webstedet ved hjælp af deres egne personlige adgangskoder, men kan kun udføre de valgte funktioner på administratorens vegne. Når som helst kan en administrator ændre en autoriseret brugers personlige adgangskode for at forhindre hans eller hendes adgang til webstedet, begrænse den autoriserede brugers autoritet til at udføre bestemte funktioner på vegne af medlemmet eller på anden måde ændre, tilføje eller slette autoriserede brugere. Hvis en autoriseret bruger ikke længere er autoriseret til at handle på dine vegne, er administratoren ansvarlig for at bruge disse sikkerhedsprocedurer, som vi har stillet til rådighed for dig for at opsige eller begrænse den autoriserede brugers adgang til webstedet.</h5>
                                    <h5 className="mb-30 mt-10">Du modtager en adgangskode og kontobetegnelse, når du har gennemført oplysningerne om medlemskontoen. Hvis du er administrator af din medlemskabskonto, i betragtning af din brug af webstedet, accepterer du:
                                    </h5>
                                    <ul>
                                        <strong>1. </strong>At give ægte, nøjagtige, aktuelle og komplette oplysninger om dig selv og / eller det firma, du repræsenterer, inklusive men ikke begrænset til oplysninger om alle autoriserede brugere; herunder eventuelle særlige omstændigheder eller begrænsninger, der gælder for hver autoriseret bruger.<br />
                                        <strong>2. </strong>At du repræsenterer og garanterer, at du har kapacitet og myndighed til at udføre aftaler og afgive ordrer på Green Plank-produkter og -tjenester på vegne af dig eller din virksomhed.<br />
                                        <strong>3. </strong>At en ordre, der er afgivet af dig eller en autoriseret bruger via webstedet, svarer til en underskrevet indkøbsordre, og du afstår hermed fra enhver fremtidig udfordring med hensyn til gyldigheden og håndhævelsen af ​​enhver ordre, der afgives via webstedet med den begrundelse, at den blev sendt elektronisk og autoriseret.<br />
                                        <strong>4. </strong>At du er ansvarlig for alle omkostninger og gebyrer, inklusive uden begrænsning, telefonafgifter og telekommunikationsudstyr, der er afholdt for at bruge webstedet.<br />
                                        <strong>5. </strong>At du (og din virksomhed, hvis relevant) er fuldt ansvarlig for alle aktiviteter, der finder sted under din adgangskode eller medlemskontokonto, og accepterer ethvert ansvar for handlinger eller undladelser fra dine autoriserede brugere, der måtte opstå som følge af deres brug af webstedet, selvom sådan handlinger eller undladelser er ikke specifikt godkendt af dig.<br />
                                        <strong>6. </strong>Til straks at underrette os om enhver uautoriseret brug af din adgangskode eller medlemskonto eller enhver anden sikkerhedsbrud.<br />
                                    </ul>
                                    <h3 className="mb-30 mt-30">EJENDOMS INDHOLD</h3>
                                    <p className="mb-30 mt-10">Alt indhold, der er inkluderet på dette websted, tilhører Green Plank og / eller dets forskellige tredjepartsudbydere og distributører og er beskyttet under lovgivningen om intellektuel ejendomsret i Sverige og andre lande. Intet af indholdet, der findes på dette websted, må reproduceres, genudgives, distribueres, vises, sælges, overføres eller ændres uden udtrykkelig skriftlig tilladelse fra Green Plank og / eller tredjepartsudbydere og distributører.</p>

                                    <h3 className="mb-30 mt-30">OPHAVSRET</h3>
                                    <p className="mb-30 mt-10"> Alt ophavsretsligt beskyttet og ophavsretligt beskyttet materiale på dette websted, inklusive, uden begrænsning, Green Plank-logoet, design, tekst, grafik, billeder og andre filer og valg og arrangement (“Materialer”) deraf tilhører Green Plank, ALL RETTIGHEDER FORBEHOLDT Copyright © 2010 Green Plank AB og / eller dets licensgivere. Bortset fra som angivet heri, må intet af materialet kopieres, reproduceres, distribueres, genudgives, downloades, vises, indsendes eller transmitteres i nogen form eller på nogen måde, herunder, men ikke begrænset til, elektronisk, mekanisk, fotokopiering, optagelse eller ellers uden forudgående skriftlig tilladelse fra Green Plank eller den respektive ophavsretsejer.</p>

                                    <h3 className="mb-30 mt-30">VAREMÆRKER OG TJENESTEMÆRKER</h3>
                                    <p className="mb-30 mt-10">Green Plank, Green Plank-logoet og de produkter og tjenester, der er beskrevet på dette websted, inklusive uden begrænsning, “Green Plank”, er enten varemærker, servicemærker eller registrerede varemærker tilhørende Green Plank og dets leverandører og licensgivere og kan ikke kopieres , efterlignet eller brugt, helt eller delvist uden forudgående skriftlig tilladelse fra Green Plank eller dets leverandører eller licensgivere. Derudover er alle sideoverskrifter, brugerdefineret grafik, knapikoner og scripts servicemærker, varemærker og / eller handelsdrag fra Green Plank og må ikke kopieres, efterlignes eller bruges, helt eller delvist uden forudgående skriftlig tilladelse fra Green Plank. Alle andre varemærker, registrerede varemærker, produktnavne og Green Plank navne eller logoer nævnt heri tilhører deres respektive ejere.</p>

                                    <h3 className="mb-30 mt-30">ANVENDELSE AF STEDET</h3>
                                    <p className="mb-30 mt-10"> Green Plank giver dig en begrænset licens til at bruge dette websted, til at foretage legitime ordrer og køb og må ikke bruge dette websted til andre formål, herunder uden begrænsning, til at foretage spekulative, falske eller falske ordrer eller nogen ordre i forventning om efterspørgsel. Sådan tildeling inkluderer ikke uden begrænsning: (a) nogen videresalg eller kommerciel brug af webstedet og / eller teknologien eller indholdet deri; (b) indsamling og anvendelse af produktfortegnelser eller beskrivelser (c) gør afledte anvendelser af webstedet og dets indhold; eller (d) anvendelse af data mining, robotter eller lignende dataindsamlings- og ekstraktionsmetoder. Bortset fra som nævnt ovenfor overføres du ikke nogen rettigheder eller licenser underforstået, estoppel eller på anden måde i eller under nogen patenter, varemærker, ophavsret eller ejendomsret til Green Plank eller nogen tredjepart.</p>
                                    <p className="mb-30 mt-10"> Dette websted og indholdet på dette websted må ikke kopieres, reproduceres, genudgives, uploades, indsendes, transmitteres eller distribueres uden skriftlig tilladelse fra Green Plank, bortset fra at du kan downloade, vise og udskrive det materiale, der præsenteres på dette websted til kun licenserede formål forudsat at du ikke må, uden tilladelse fra Green Plank eller den respektive ophavsretsejer, (a) kopiere, offentliggøre eller poste noget materiale på noget websted, computernetværk eller udsendelses- eller publikationsmedier, (b) ændre materialet, og (c) fjerne eller ændre ophavsret, varemærke og andre beskyttede meddelelser indeholdt i materialet. Uautoriseret brug af dette websted og / eller det materiale, der er indeholdt på dette websted, kan krænke gældende ophavsret, varemærke eller anden intellektuel ejendomsret eller anden lovgivning.</p>
                                    <p className="mb-30 mt-10"> Du må ikke bruge, indramme eller bruge indramningsteknikker til at vedlægge Green Plank-varemærke, logo eller anden proprietær information (inklusive de billeder, der findes på dette websted, indholdet af teksten eller layoutet / designet på en side eller form indeholdt på en side ) uden Green Planks udtrykkelige skriftlige samtykke. Yderligere må du ikke bruge metatags eller anden “skjult tekst”, der bruger et Green Plank-navn, varemærke eller produktnavn uden Green Planks udtrykkelige skriftlige samtykke.</p>

                                    <h3 className="mb-30 mt-30">ALDER OG ANSVAR</h3>
                                    <p className="mb-30 mt-10"> Du erklærer, at du er tilstrækkelig lovlig til at bruge dette websted og skabe bindende juridiske forpligtelser for ethvert ansvar, du måtte pådrage dig som følge af brugen af ​​dette websted. Du forstår, at du er økonomisk ansvarlig for al brug af dette websted af dig og dem, der bruger dine loginoplysninger.</p>

                                    <h3 className="mb-30 mt-30">AFSLUTNING</h3>
                                    <p className="mb-30 mt-10">Du accepterer, at Green Plank efter eget skøn kan opsige din eller enhver autoriseret brugers adgangskode, konto eller brug af webstedet eller begrænse din eller enhver autoriseret brugers adgang til enhver komponent på dette websted, uanset årsag, inklusive uden begrænsning, på grund af manglende brug, eller hvis Green Plank mener, at du eller en autoriseret bruger har overtrådt eller handlet i strid med brugsbetingelserne eller gældende love eller regler. Green Plank kan også efter eget skøn og til enhver tid ophøre med at levere Webstedet eller en hvilken som helst del deraf med eller uden varsel. Du accepterer, at enhver afbrydelse af adgangen til webstedet under enhver bestemmelse i brugsbetingelserne kan ske uden varsel og anerkender og accepterer, at Green Plank straks kan deaktivere eller slette din medlemskonto og alle relaterede oplysninger og filer på din konto og / eller forhindre yderligere adgang til sådanne filer eller webstedet. Yderligere accepterer du, at Green Plank ikke hæfter over for dig eller nogen tredjepart for nogen opsigelse eller begrænsning af adgangen til webstedet.</p>

                                    <h3 className="mb-30 mt-30">FRASKRIVELSE AF GARANTIER OG REPRÆSENTATIONER</h3>
                                    <p className="mb-30 mt-10"> DIN BRUG AF STEDET ER PÅ DIN ENESTE RISIKO. SIDEN OG MATERIALERNE DER LEVERES “SOM DE ER” OG “SOM TILGÆNGELIG” GRUNDLAG. DU ANERKENDER, AT DU ER RÅDET AF GRØN PLANK, TIL AT TAGE DIN EGNE FORHOLD MED HENSYN TIL DETTE SIDE. GRØN PLANKE GIVER INGEN REPRÆSENTATIONER ELLER GARANTIER, UDTRYKT ELLER UNDERFORSTÅET, FOR NOGET SORT MED HENSYN TIL DEN GRØNNE PLANKE, DETS BETJENING, INDHOLD, INFORMATION, MATERIALER.</p>
                                    <p className="mb-30 mt-10"> GRØN PLANK FRASKRIVER UDTRYKKELIGT ALLE REPRÆSENTATIONER OG GARANTIER, UDTRYKT ELLER UNDERFORSTÅET, FOR ALLE TYPER VEDRØRENDE DETTE WEBSTED ELLER DETS BRUG, INKLUDERENDE, MEN IKKE BEGRÆNSET TIL SALGSBARHED, EGNETHED TIL EN SÆRLIG OVERENSSTEMMELSE, NØJAGTIGHED INDHOLDET ELLER DATA FUNDET PÅ DETTE WEBSTED, AFSNIT OG IKKE-OVERTRÆDELSE, OG DE, DER OPSTÅR VED STATUT ELLER ANDET I LOVGIVNING ELLER EGENKAPITAL, ELLER FRA KURSER FOR HANDLING ELLER BRUG AF HANDEL.</p>

                                    <h3 className="mb-30 mt-30">ANSVARSBEGRÆNSNING</h3>
                                    <p className="mb-30 mt-10"> DU ER ENIGE I, AT GRØN PLANKE, DENS DIREKTØRER, KONTRAKTER, MEDARBEJDERE ELLER ANDRE REPRÆSENTANTER IKKE ER ANSVARLIGE FOR SKADER, DER OPSTÅR FRA BETJENING, INDHOLD, ADGANG TIL ELLER BRUG AF SIDEN. DU ER ENIGE I, AT DENNE BEGRÆNSNING AF ANSVAR ER OMFATTENDE OG GÆLDER FOR ALLE SKADER AF ALLE SLAG, INKLUDERET UDEN BEGRÆNSNINGER DIREKTE, INDIREKTE, KOMPENSERENDE, SPECIALE, TILFÆLDIGE, PUNITIVE OG FØLGENDE SKADER INKLUDERENDE, MULIGE SKADER, BEGRÆNSEDE FOR SKADER BRUG, DATA ELLER ANDRE IMMATERIELLE TAB (SELV HVIS DEN GRØNNE PLANKE ER RÅDET TIL MULIGHEDEN FOR SÅDANE SKADER) DEN GRUNDLIGE ANSVAR (GRUNDLÆGGENDE), PRODUKTANSVAR, STRIKKET ANSVAR ELLER ANDEN TEORI) SKAL IKKE HVILKE ANSVAR FOR GRØN PLANKE, PRODUKTANSVAR ELLER ANDEN TEORI DU BETALTE GRØN PLANK, SOM ALT ER MINDRE.</p>
                                    <p className="mb-30 mt-10"> Visse love tillader ikke begrænsninger af underforståede garantier eller udelukkelse eller begrænsning af visse skader. Hvis disse love finder anvendelse, gælder nogle af eller alle ovenstående ansvarsfraskrivelser, udelukkelser eller begrænsninger muligvis ikke for dig, og du har muligvis yderligere rettigheder til dem, der er indeholdt heri.</p>

                                    <h3 className="mb-30 mt-30">ERSTATNING</h3>
                                    <p className="mb-30 mt-10"> Du skal skadesløse, forsvare og holde Green Plank uskadelig og dets officerer, direktører, medarbejdere, konsulenter, repræsentanter og agenter fra og mod ethvert tab, erstatningsansvar, krav, sag, sag, erstatning, omkostninger eller udgifter inklusive uden begrænsning rimelig juridisk, regnskabsmæssige og andre professionelle gebyrer, bragt af eller på dine vegne ud over det ansvar, der er beskrevet heri eller af tredjeparter, der opstår som følge af eller i forbindelse med din brug eller nogen af ​​dine autoriserede brugeres brug af dette websted, herunder men ikke begrænset enhver overtrædelse af dig eller en autoriseret bruger af brugsbetingelserne. Green Plank forbeholder sig retten til at påtage sig det eksklusive forsvar og kontrol af ethvert spørgsmål med forbehold for skadesløsholdelse fra dig, hvilket ikke undskylder dine skadesløsholdelser.</p>

                                    <h3 className="mb-30 mt-30">VÆRKTØJ & FUNKTIONER</h3>
                                    <p className="mb-30 mt-10"> Alle værktøjer, funktioner, regnemaskiner osv. Leveres kun som en tilladelse. Alle resultater er estimater og skal bruges som sådan. Green Plank kan ikke holdes ansvarlig eller ansvarlig for information, der stammer fra brugen af ​​de leverede værktøjer og funktioner på www.GreenPlank.dk</p>

                                    <h3 className="mb-30 mt-30">HVOR KØB / FIND EN PRO / FÅ ET PRIS</h3>
                                    <p className="mb-30 mt-10"> Green Plank garanterer ikke, at vi vil være i stand til at matche dine servicebehov med en serviceperson, eller at der er servicepersonale i dit område, der enten er i stand til eller villige til at udfylde dine servicebehov. Selvom vi tager visse skridt til at undersøge legitimationsoplysninger fra vores børsnoterede servicepersonale, giver Green Plank ingen garantier eller erklæringer angående en sådan serviceprofessionals kvalifikationer eller repræsentationer eller kvaliteten af ​​det job, som han eller hun kan udføre for dig, hvis du vælger at beholde deres tjenester. Green Plank godkender eller anbefaler ikke tjenester fra en bestemt servicepersonale. Det er helt op til dig at indgå en direkte kontrakt eller på anden måde nå til enighed med en serviceperson, og vi garanterer eller garanterer ikke deres udførelse på jobbet eller resultatet eller kvaliteten af ​​de udførte tjenester. Servicepersonalet er ikke ansatte eller agenter for Green Plank, og Green Plank er heller ikke en agent for servicepersonalet. Green Plank udfører ikke og er ikke ansvarlig for nogen af ​​de tjenester, du anmoder om i din serviceanmodning. Dine rettigheder i henhold til kontrakter, du indgår med servicepersonale, er underlagt vilkårene i sådanne kontrakter og af gældende føderale, statslige, provinsielle og lokale love. Hvis du har en tvist med en serviceprofessional, skal du adressere en sådan tvist med servicepersonalet direkte, OG DU GODKENDER hermed samtykke til at frigive den GRØNNE PLANK (OG VORES TJENESTEMÆND, DIREKTØRER, FIRMA, MEDARBEJDERE OG AGENTER) OG EN ANDEN PERSON, FIRM ELLER ENHED (INKLUSIVT VORES VIRKSOMHEDSPARTNERE SOM PRODUKTFREMSTILLER ELLER LEVERANDØR, DER KAN ANVENDE DEN GRØNNE PLANKE MATCHING UTILITY) FRA ALLE SKADER ELLER KRAV (INKLUDERENDE FØLGENDE OG TILFÆLDIGE SKADER, ULIGE SKADER ELLER SKADE, UNDTAGELIGE SKADER ELLER UNDGÅRT ELLER UDVIDT, OPSTÅENDE UD ELLER PÅ ENGEN MÅDE FORBINDET MED SÅDANE TVISTER OG DINE FORHANDLINGER MED TJENESTEFAGLIGE.</p>

                                    <h3 className="mb-30 mt-30">LINKS</h3>
                                    <p className="mb-30 mt-10"> Dette websted kan indeholde links til andre websteder, der udelukkende leveres som en bekvemmelighed for dig, og inkluderingen af ​​ethvert link betyder ikke, at Green Plank godkender, efterforsker eller verificerer det linkede websted eller information deri. Green Plank er ikke ansvarlig for indholdet af andre websteder og giver ingen garanti for andre websteder eller indholdet eller materialet på sådanne websteder. Hvis du beslutter at få adgang til andre websteder, gør du det på egen risiko.</p>

                                    <h3 className="mb-30 mt-30">FORBINDELSE</h3>
                                    <p className="mb-30 mt-10"> Forholdet mellem Green Plank og dig vil være uafhængigt entreprenørers forhold, og hverken af ​​os eller nogen af ​​vores respektive officerer, agenter eller medarbejdere vil blive holdt eller fortolkes som værende partnere, joint ventures, forvaltere, medarbejdere eller agenter for den anden som en resultat af denne aftale eller brug af dette websted.</p>

                                    <h3 className="mb-30 mt-30">LOVVALG</h3>
                                    <p className="mb-30 mt-10"> Denne aftale og dens udførelse er underlagt lovgivningen i Sverige for alle forhold, der opstår fra eller i forbindelse med brugen af ​​dette websted, hvad enten det gælder krav i kontrakt, erstatningsret eller på anden måde uden hensyntagen til dets lovbestemmelser. Du og Green Plank er enige om, at enhver sag, der måtte opstå i henhold til denne aftale, skal påbegyndes og behandles for den relevante domstol i Sverige, amt Skåne. Du og Green Plank er begge enige om at underkaste sig den personlige og eksklusive jurisdiktion for domstolene i Skåne i Sverige. Green Planks undladelse af at udøve eller håndhæve nogen rettigheder eller bestemmelser i brugsbetingelserne udgør ikke et afkald på en sådan ret eller bestemmelse. Hvis en bestemmelse i brugsvilkårene af en domstol med kompetent jurisdiktion anses for at være ugyldig, er parterne alligevel enige om, at domstolen skal bestræbe sig på at gennemføre parternes intentioner som afspejlet i bestemmelsen og de øvrige bestemmelser i vilkårene brug forbliver i fuld kraft og virkning. Du accepterer, at uanset hvilken lov eller anden lov, der er modsat, skal ethvert krav eller en årsag til handling fra dig, der opstår som følge af eller er relateret til brugen af ​​Produkterne og tjenesterne eller brugsvilkårene, indgives inden for en (1) måned efter et sådant krav. eller en årsag til handling opstod eller er for altid udelukket.</p>

                                    <h3 className="mb-30 mt-30">OPDRAG</h3>
                                    <p className="mb-30 mt-10"> Du må ikke overdrage, formidle, udlicitere eller uddelegere dine rettigheder, pligter eller forpligtelser i henhold hertil.</p>

                                    <h3 className="mb-30 mt-30">HELE AFTALEN</h3>
                                    <p className="mb-30 mt-10">Disse brugsbetingelser, sammen med dem, der er inkorporeret heri eller henvist til heri, udgør hele aftalen mellem os vedrørende emnet heraf, og det erstatter enhver tidligere forståelse eller aftale (hvad enten det er elektronisk, mundtligt eller skriftligt) om emnet og kan ikke ændres eller modificeres undtagen skriftligt eller ved at gøre sådanne ændringer eller ændringer tilgængelige på dette websted.</p>

                                </div>
                            </Col>
                        </Row>
                    </Container>
                </section>
                <BrandCarousel />
                <Footer />
            </Layout>
        </>
    );
};

export default Betingelser;
