import React from "react";
import Layout from "../components/layout";
import HeaderTwo from "../components/header/header-two";
import StickyHeader from "../components/header/sticky-header";
import PageHeader from "../components/page-header";
import BrandCarousel from "../components/brand-carousel";
import { Container, Row, Col } from "react-bootstrap";
import Footer from "../components/footer";
import Head from "next/head";

const Salgsbetingelser = () => {
    return (
        <>
            <Head>
                <title>Salgsbetingelser</title>
                <meta name="title" content="Salgsbetingelser - GreenPlank.dk" />
                <meta name="description" content="Läs det här dokumentet noggrant. Den innehåller viktig information om dina rättigheter och skyldigheter samt begränsningar och uteslutningar som gäller dig." />
            </Head>
            <Layout pageTitle="Salgsbetingelser">
                <HeaderTwo />
                <PageHeader title="Salgsbetingelser" crumbTitle="salgsbetingelser" />
                <StickyHeader />
                <section className="about-one pt-120 pb-40">
                    <Container>
                        <Row style={{ marginBottom: "4em" }}>
                            <Col lg={12}>
                                <h2>Salgsbetingelser</h2>
                                <div className="mb-30">
                                    <p>LÆS venligst dette dokument nøje. DET INDEHOLDER VIGTIG INFORMATION OM DINE RETTIGHEDER OG FORPLIGTELSER, SOM SOM BEGRÆNSNINGER OG UDELUKKELSER, DER GÆLDER FOR DIG.</p>
                                    <p className="mb-30 mt-30">Denne aftale indeholder de vilkår og betingelser, der gælder for kunder ved køb fra Green Plank AB. (i det følgende benævnt “Green Plank”) og den “Green Plank” enhed, der er nævnt på fakturaen, der vil blive leveret til dig (kunde) på ordrer på solgte produkter. Kunden accepterer at være bundet af og acceptere denne aftale, som det er relevant for kunder, der køber produkter fra Green Plank og / eller Green Plank internetwebsite, der i det følgende benævnes webstedet. Som en salgsbetingelse accepterer kunden at være bundet af og accepterer disse vilkår og betingelser. Disse vilkår og betingelser gælder (i) medmindre kunden har underskrevet en separat formel købsaftale med Green Plank, i hvilket tilfælde den separate aftale gælder; eller (ii) medmindre andre Green Plank-standardbetingelser gælder for transaktionen som nævnt heri eller andetsteds. Disse vilkår og betingelser kan ændres uden forudgående skriftlig varsel til enhver tid efter Green Planks eget skøn.</p>
                                    <p className="mb-30 mt-30">DIN accept af disse vilkår og betingelser for salg er inkluderet i din accept af vilkårene og brugen af ​​denne hjemmeside.</p>
                                    <h3 className="mb-30 mt-30"><strong>1. </strong>BESTIL POLITIK FOR ACCEPT</h3>
                                    <p className="mb-30 mt-30">Kundemodtagelse af en elektronisk eller anden form for ordrebekræftelse betyder ikke, at Green Planks accepterer Kundens ordre, og det udgør heller ikke en bekræftelse af Green Planks tilbud om at sælge. Alle ordrer accepteres i Malmø, Sverige. Green Plank forbeholder sig retten til enhver tid efter modtagelse af Kundens ordre til at acceptere eller afvise Kunders ordre af rimelig grund, herunder men ikke begrænset til manglende tilgængelighed af produkter, Kundens manglende opfyldelse af betalingsbetingelser og / eller Kundens misligholdelse af denne Aftale . Hvis betalingen er tilbagebetalt for købet, og Green Plank annullerer kundernes ordre, skal Green Plank straks udstede en refusion svarende til det beløb, der er tilbagebetalt for den uaccepterede eller annullerede ordre.</p>
                                    <h3 className="mb-30 mt-30"><strong>2. </strong>BETALINGSBETINGELSER</h3>
                                    <p className="mb-30 mt-30">Betalingsbetingelserne er inden for Green Planks eget skøn, og medmindre andet er aftalt af Green Plank, skal betaling være modtaget eller på anden måde godkendt eller sikret i en form, der er godkendt af Green Plank, inden Green Planks accepterer en ordre. Betaling for produkterne sker med godkendt kreditkort, bankoverførsel, elektronisk pengeoverførsel eller anden forudbestemt betalingsmetode, der er aftalt med Green Plank. Fakturaer forfalder og betales inden den / de betalingsdatoer, der er angivet via elektronisk (inklusive men ikke begrænset til e-mail), fax (fax) og / eller mundtlig bekræftelse mellem Green Plank og kunden. Green Plank kan fakturere dele af en ordre separat. Ordrer er ikke bindende for Green Plank, før de er accepteret af Green Plank (se Orderacceptance Policy). Alle tilbud fra Green Plank er gyldige i den periode, der er angivet på tilbuddet. Green Plank forbeholder sig ret til at justere eller annullere tilbud efter behov.</p>
                                    <h3 className="mb-30 mt-30"><strong>3. </strong>FORSENDELSE</h3>
                                    <p className="mb-30 mt-10">Kunden er ansvarlig for alle omkostninger i forbindelse med forsendelse af produkt til det sted, der er specificeret af kunden. Det er kundernes ansvar at give kontaktoplysninger, der gør det muligt for afsenderen at kontakte kunden, når forsendelsen foretages. Forsendelsespriser gælder kun for standard afhentning og levering. Kunden er ansvarlig for at losse varerne fra transportøren. Yderligere opbevarings- og / eller forsendelsesomkostninger og andre lagerafgifter kan være gældende, hvis kunden ikke kan kontaktes eller ikke er tilgængelig for at modtage produktet; eller hvis produktet omdirigeres efter kundens anmodning. Hvis en forsendelsespris er angivet med en forkert sats på grund af typografiske fejl eller fejl i prisoplysninger modtaget fra Green Planks leverandører, har Green Plank ret til at afvise, justere eller annullere ordrer, uanset om ordren er bekræftet eller ej om betaling er blevet overført. Kunden er ansvarlig for at inspicere fragt for mangel eller tegn på skade ved modtagelse af varer. Alle fragt-, tabs- og skadesanmodninger skal indgives til Green Plank inden for syv (7) arbejdsdage fra datoen for afsendelse. (se 10. Begrænsninger for skader eller kontakt os på: info@GreenPlank.eu.) Green Plank er ikke ansvarlig for forsinkelse eller fiasko i udførelsen eller ved levering eller forsendelse af materialer eller merchandise eller for eventuelle skader, som Kunden har lidt grund til en sådan forsinkelse eller fiasko, når en sådan forsinkelse eller fiasko direkte eller indirekte skyldes eller på nogen måde skyldes eller er forbundet med handlinger fra Gud, handlinger fra offentlige fjender, optøjer, handlinger fra regeringsorganer, arbejdsvanskeligheder, leverandørers manglende sende eller producere varer, forsinkelse i sikring eller mangel på råvarer, nedbrydning eller destruktion af anlæg eller udstyr eller enhver anden årsag eller årsager uden for Green Plank’s kontrol, uanset om de ligner dem, der er opregnet heri. Alle ordrer betragtes som suspenderede, så længe enhver sådan årsag forhindrer eller forsinker ydeevne eller levering eller forsendelse.</p>
                                    <h3 className="mb-30 mt-30"><strong>4. </strong>SKATTER</h3>
                                    <p className="mb-30 mt-10">Kunden er ansvarlig for alt salg, brug, punktafgift, merværdiafgift og andre gebyrer, der er knyttet til ordren, uanset hvor de er udpeget, inklusive eventuelle afgifter, afgiftsafgifter eller andre destinationsafgifter. Hvis det er relevant, vises en separat afgift for sådanne varer på Green Planks faktura.</p>
                                    <h3 className="mb-30 mt-30"><strong>5. </strong>LEVERINGSSKADE</h3>
                                    <p className="mb-30 mt-10">Ved ankomst tjek din pakke for skader. Hvis du oplever skader, skal du notere dem på fragtbrevet, når du underskriver pakken, eller hvis der ikke kræves nogen underskrift, skal du straks kontakte rederiet. Hvis der ikke er registreret nogen skader på fragtbrevet, kan Green Plank ikke holdes ansvarlig for skader. Når det er anført på fragtbrevet, og du finder ud af, at du ikke kan bruge produktet, skal du kontakte Green Plank via e-mail eller telefon for at rapportere det beskadigede materiale. Hvis du tilfældigvis accepterer en forsendelse og underskriver ingen skader, og senere opdager, at der faktisk er skader, skal du kontakte transportvirksomheden inden for 48 timer efter levering for at rapportere det. Green Plank kan ikke indgive krav på dine vegne efter femten (15) arbejdsdage fra leveringstidspunktet eller forsøg på levering.</p>
                                    <h3 className="mb-30 mt-30"><strong>6. </strong>ANNULLERINGER</h3>
                                    <p className="mb-30 mt-10">Du har ret til at annullere ordren når som helst inden for 24 timer fra det tidspunkt, du modtog ordrebekræftelse fra Green Plank. Du bliver nødt til at kontakte Green Plank via e-mail eller telefon hurtigst muligt. Hvis dit køb allerede er afsendt, skal du sørge for en retur, og du er ansvarlig for forsendelsesomkostninger + 20% genopfyldningsgebyr. Hvis købet ikke er afsendt, kan du annullere uden beregning til din oprindelige betalingsmetode, ekskl. Transaktionsgebyrer.</p>
                                    <p>Ordrer foretaget af detailhandlere eller grossister, specialordrer og specialdesign, farve, model, størrelse osv., Ordrer kan ikke annulleres, når de er bekræftet af Green Plank.</p>
                                    <h3 className="mb-30 mt-30"><strong>7. </strong>VENDER TILBAGE</h3>
                                    <p className="mb-30 mt-10">Hvis du ombestemmer dig, kan du returnere ubrugte eller uåbnede varer inden for syv (7) dage efter levering for en refusion (desværre refunderes eventuelle forsendelsesomkostninger ikke). Varer skal returneres i ny, uåbnet og ubrugt stand og indeholder alt originalt materiale, der følger med forsendelsen. Returnerede genstande er underlagt et 20% genopfyldningsgebyr. Kontakt os for et RMA-nummer (Return Merchandise Authorization), hvis du vil returnere. Ved returnering kræves et RMA-nummer.</p>
                                    <p>
                                        Når din (e) vare (r) er modtaget i vores lager, bliver den inspiceret. Hvis varen returneres i ny, uåbnet og ubrugt stand, får du en refusion til den oprindelige købspris plus moms, hvis det er relevant i den originale betalingsmetode, minus 20% genopfyldningsgebyr minus forsendelsesomkostninger inden for fire uger efter forsendelse af din pakke til os. Hvis returneringen er et resultat af vores fejl, bedes du angive det på returemballagesedlen, og vi udsteder en refusion til den oprindelige købspris plus moms, hvis relevant plus forsendelsesomkostninger i den originale betalingsmetode.</p>
                                    <h3 className="mb-30 mt-30"><strong>8. </strong>AFSLAG</h3>
                                    <p className="mb-30 mt-10">Hvis pakken nægtes ved ankomst, er du ansvarlig for leverings- og returforsendelsesomkostninger + 20% genopfyldningsgebyr. Eventuelle skader fra nægtede leverancer refunderes ikke, og fordi de blev nægtet, ville de ikke blive noteret. Vi er ikke ansvarlige for NOE omkostninger forbundet med en afvist levering.</p>
                                    <h3 className="mb-30 mt-30"><strong>9. </strong>GARANTIER</h3>
                                    <p className="mb-30 mt-10">Alle angivne garantier er kun producent / produktspecifikke garantier. Green Plank giver ingen udtrykkelige garantier undtagen dem, der er angivet i denne aftale og i Green Planks gældende garantierklæring, der er gældende på fakturadatoen. Enhver sådan garanti vil være effektiv, og Green Plank er forpligtet til at respektere sådanne garantier, kun efter Green Planks modtagelse af den fulde betaling for varen, der er berettiget. Inden du returnerer en vare, skal kunden kontakte Green Planks Claims Department. for et garantitilladelsesnummer (WA) inden for den tilladte periode, der er specificeret af producenten af ​​produktet (se produktspecifik garanti). WA-nummeret er kun gyldigt for det produkt, der er beskrevet deri. Det returnerede produkt skal matche det produkt, der er godkendt til returnering. Kunden skal sikre, at alle returneringer modtages af producenten / leverandøren inden for tredive (30) dage efter modtagelse af WA-nummeret. Alle forsendelsesordninger for retur eller bytte skal behandles gennem Green Planks Logistics Department. Kunden er ansvarlig for alle forsendelses- og håndteringsomkostninger i forbindelse med garantireturer, undtagen hvor producenten af ​​produktet har aftalt at betale for sådanne omkostninger eller som beskrevet under produktgarantien. Når det er muligt eller som beskrevet under garantien, skal alle varer være i en ny stand , i original emballage og med alle garantikort, manualer og tilbehør. Den originale følgeseddel skal medtages, og WA-nummeret skal være synligt på pakken. Green Plank kan kræve en kort skriftlig forklaring og et fotografi eller digitalt billede af det defekte produkt. I nogle tilfælde kræves der en inspektion på stedet af produktet. Green Planks Claims Department vil informere kunden om de detaljer, der er specifikke for garantikravet.

                                    </p>
                                    {/* <p>
                                        Plank är skyldig att respektera sådana garantier, endast efter att Green Plank mottagit full betalning för att varan ska garanteras. Innan ni returnerar en vara måste kunden kontakta Green Planks Skade avdelning. för ett garanti nummer (WA) inom den tillåtna perioden som anges av tillverkaren av produkten (se produkt specifik garanti). WA-numret är endast giltigt för den produkt som beskrivs där. Den returnerade produkten måste matcha den produkt som är godkänd för retur. Kunden måste se till att alla returer tas emot av tillverkaren / leverantören inom trettio (30) dagar från det att WA-numret erhållits. Alla leverans arrangemang för retur eller byte måste behandlas via Green Planks logistik avdelning. Kunden ansvarar för alla leverans- och hanterings avgifter för garanti returer, förutom där tillverkaren av produkten har gått med på att betala för sådana kostnader eller som beskrivs under produkt garantin. När det är möjligt eller enligt beskrivningen under garantin måste alla artiklar i nytt skick, i original förpackning och med alla garanti kort, manualer och tillbehör. Original paketet måste ingå och WA-numret syns på förpackningen. Green Plank kan kräva en kort skriftlig förklaring och ett fotografi eller en digital bild av den defekta produkten. I vissa fall krävs en inspektion på plats av produkten. Green Planks Skade avdelning kommer att informera kunden om detaljerna specifika för garanti anspråket.</p> */}
                                    {/* <p>
                                        GARANTIERNA I DETTA AVTAL ÄR TILLVERKARE / PRODUKT SPECIFIKA GARANTIER FÖR PRODUKTEN (ER). GREEN PLANK FÖREDRAR UTTRYCKLIGA ÖVRIGA GARANTIER, GARANTIER ELLER UTFÖRANDE, VID UTTRYCKT, UNDER FÖRSTÄLL ELLER FÖRESKRIFTER, INKLUDERANDE UNDERFÖRSTÅDD GARANTI FÖR SÄLJBARHET ELLER FITNESS FÖR ETT SÄRSKILT SYFTE. GREEN PLANK FRISKRIVNING OCH ALLA UNDERFÖRSTÅDDA GARANTIER FÖR HANDELS ANVÄNDNING ELLER UTFÖR ETT KURS FÖR HANDLING ELLER UTFÖRANDE AV PRESTANDA. GREEN PLANK GARANTERAR INTE ATT PRODUKTEN ÄR FELFRI ELLER GARANTERAR ATT VARJE FEL KORRIGERAS. GREEN PLANK GARANTERAR INTE ATT ALLA PRODUKTER FÖLJER SPECIFIK GEOGRAFISK ÖVERENSSTÄMMELSE ELLER FÖRESKRIFTER. DET ÄR KUNDENS ANSVAR FÖR ATT SÄKRA ATT ANVÄNDNING AV KÖPTA PRODUKTER ÖVERENSSTÄMMER MED LOKALA JURISDIKTIONS KODER OCH MED ALLA REGIONALA, NATIONELLA OCH INTERNATIONELLA LAGAR OCH REGLER. GREEN PLANK FRÅN FRÅN FRÅGAR PATENT / INTELLEKTUELL FASTIGHETS RÄTTIGHETER, GARANTIER ELLER ERSÄTTNINGAR MED HÄNVISNING TILL NÅGOT LÅSNING / ANSLUTNINGS SYSTEM (ER) ANVÄNDA AV TILLVERKARE AV LAMINAT, ENGINEERAD TRÄ ELLER ANDRA PRODUKTER SÅLDA AV GREEN PLANK.</p> */}
                                    <h3 className="mb-30 mt-30"><strong>10. </strong> ANSVARSFRASKRIVELSE</h3>
                                    <p className="mb-30 mt-10">Garantierne i denne aftale er producent / produktspecifikke garantier for produktet / produkterne. Green Plank fraskriver sig udtrykkeligt alle andre garantier, garantier eller repræsentationer, hvad enten de er udtrykkelige, underforståede eller lovbestemte, herunder enhver underforstået garanti for salgbarhed eller egnethed til et bestemt formål. Green Plank fraskriver sig også enhver underforstået garanti, der opstår som følge af handelsanvendelse eller som følge af et handelsforløb eller ydeevne. Green Plank garanterer ikke, at produktet / produkterne er fejlfrie, eller garanterer, at hver defekt vil blive rettet. Green Plank garanterer ikke, at alle produkter overholder specifik geografisk overensstemmelse eller lovgivningsmæssige begrænsninger. Det er kundernes ansvar at sikre, at brug af købte produkter overholder lokale jurisdiktionskoder og med alle regionale, nationale og internationale love og regler. Green Plank fraskriver sig endvidere alle patenter / intellektuelle ejendomsrettigheder, garantier eller skadesløsholdelse med hensyn til ethvert låse / tilslutningssystem (er), der anvendes af producenter af laminat, konstrueret træ eller andre produkter solgt af Green Plank.</p>
                                    <h3 className="mb-30 mt-30"><strong>11. </strong> BEGRÆNSNING AF SKADER</h3>
                                    <p className="mb-30 mt-10">Green Plank påtager sig ikke ansvar ud over de retsmidler, der er beskrevet heri. Green Plank hæfter ikke for tabt fortjeneste, tab af indtægter eller forretning eller andre følgeskader, særlige, indirekte eller straffende skader, selvom de kunne forudses, eller hvis grønne planke blev underrettet om muligheden for sådanne skader eller for ethvert krav af enhver tredjepart undtagen som udtrykkeligt angivet heri. Kunden accepterer, at green plank ikke er ansvarlig for ethvert ansvar i forbindelse med køb af produkter eller tjenester, eller er ansvarlig for noget skadesbeløb, der overstiger det samlede beløb, som kunden har betalt for købet (e) i henhold til denne aftale. Denne begrænsning gælder uanset hvilken form for handling (dvs. om sagen er i kontrakt eller erstatningsret, herunder uagtsomhed).</p>
                                    <h3 className="mb-30 mt-30"><strong>12. </strong>LOVVALG</h3>
                                    <p className="mb-30 mt-10">Utöver vad som specifikt anges i något separat formellt köpeavtal mellan kunden och Green Plank, får dessa villkor INTE ändras, kompletteras eller ändras genom användning av andra dokument. Varje försök att ändra, komplettera eller ändra detta dokument eller att ange en beställning för produkter som omfattas av ytterligare eller ändrade villkor är ogiltiga, såvida inte annat avtalas i ett skriftligt avtal undertecknat av både kunden och Green Plank.</p>
                                    <h3 className="mb-30 mt-30"><strong>13. </strong>ANDRE DOKUMENTER</h3>
                                    <p className="mb-30 mt-10">Bortset fra som specifikt angivet i en separat formel købsaftale mellem kunden og Green Plank, må disse vilkår og betingelser IKKE ændres, suppleres eller ændres ved brug af andre dokumenter. Ethvert forsøg på at ændre, supplere eller ændre dette dokument eller at indtaste en ordre på produkt (er), der er underlagt yderligere eller ændrede vilkår, er ugyldige, medmindre andet er aftalt i en skriftlig aftale underskrevet af både kunde og grøn Planke.</p>
                                    <h3 className="mb-30 mt-30"><strong>14. </strong> VILKÅR FOR BRUG</h3>
                                    <p className="mb-30 mt-10">Din adgang til og brug af webstedet er underlagt Green Planks brugsbetingelser. Ved at bruge dette websted angiver du din accept uden at ændre disse brugsbetingelser. Brugsbetingelserne kan til enhver tid ændres uden forudgående varsel, efter Green Planks eget skøn, så du bør ofte gennemgå brugsbetingelserne og gældende politikker fra tid til anden for at forstå de vilkår og betingelser, der gælder for din brug af webstedet. . I tilfælde af uoverensstemmelse mellem denne Aftale og Brugsbetingelserne har vilkårene i denne Aftale forrang.</p>

                                </div>
                            </Col>
                        </Row>
                    </Container>
                </section>
                <BrandCarousel />
                <Footer />
            </Layout>
        </>
    );
};

export default Salgsbetingelser;
